install git if not found

diff --git a/brewblox_ctl/deployed/brewblox-ctl b/brewblox_ctl/deployed/brewblox-ctl
--- a/brewblox_ctl/deployed/brewblox-ctl
+++ b/brewblox_ctl/deployed/brewblox-ctl
@@ -71,6 +71,19 @@ install_ctl() {
         exit 1
     fi
 
+    # Check if git is installed
+    if ! command -v git >/dev/null 2>&1; then
+        log_error "git is required to install brewblox-ctl."
+        # check if apt is installed
+        if command -v apt >/dev/null 2>&1; then
+            log_info "Installing git with apt..."
+            sudo apt update
+            sudo apt install -y git
+        else
+            log_error "apt not found. Please install git manually and try again. If you are using a Synology NAS, you can install git from the package center's community repo."
+            exit 1
+    fi
+
     # Create venv
     uv venv
 
@@ -119,7 +132,7 @@ run_ctl() {
     fi
 
     # if no venv found or uv not found, install
-    if [[ ! -d .venv ]] || ! command -v uv >/dev/null 2>&1; then
+    if [[ ! -d .venv ]] || ! command -v uv >/dev/null 2>&1 || ! uv show brewblox_ctl >/dev/null; then
         install_ctl
     fi
 
